  DROP TABLE COMENTAR;
  
  DROP TABLE FANS;
  
  DROP TABLE ACTUAR;
  
  DROP TABLE CONVERTIR;
  
  DROP TABLE PERTENECER_GRUPO;
  
  DROP TABLE GRUPO;
  
  DROP TABLE LOCALIZACIONES;
  
  DROP TABLE CAPITULOS;
  
  DROP TABLE TEMPORADAS;
  
  DROP TABLE ZOMBIE;
  
  DROP TABLE PRINCIPAL;
  
  DROP TABLE TENER_PARENTESCO;
  
  DROP TABLE PERSONAJES;
  
  DROP TABLE HACER_CASTING;
  
  DROP TABLE ACTORES;
  
  DROP TABLE PELICULAS;



    CREATE TABLE ACTORES (
    NSS VARCHAR2(12) NOT NULL,
    NOMBRE VARCHAR2(40),
    EDAD NUMBER(2),
    SEXO VARCHAR2(20),
    NACIONALIDAD VARCHAR2(20),
    FECHA_NAC DATE,
    CONSTRAINT PK_ACTORES PRIMARY KEY(NSS));

    CREATE TABLE PELICULAS(
    COD_PELI VARCHAR2(5) NOT NULL,
    ANYO NUMBER(4),
    TITULO VARCHAR2 (180),
    DIRECTOR VARCHAR2 (150),
    CONSTRAINT PK_PELICULAS PRIMARY KEY (COD_PELI)
    );



    CREATE TABLE HACER_CASTING(
    NSS VARCHAR2(12) NOT NULL,
    CODIGO_PELICULA VARCHAR2(5) NOT NULL,
    FECHA DATE,
    HACER VARCHAR2(1),
    PROTA VARCHAR2(1),
    CONSTRAINT PK_HACER_CASTING PRIMARY KEY(NSS, CODIGO_PELICULA),
    CONSTRAINT FK_CASTING_ACTOR FOREIGN KEY (NSS) REFERENCES ACTORES (NSS),
    CONSTRAINT FK_CASTING_PELIS FOREIGN KEY (CODIGO_PELICULA) REFERENCES PELICULAS (COD_PELI)
    );


    CREATE TABLE PERSONAJES (
    NOMBRE VARCHAR2 (60) NOT NULL,
    NSS_ACTOR VARCHAR2 (12) NOT NULL,    
    SEXO VARCHAR2 (10),
    PROFESION VARCHAR2 (255),
    CARACTER VARCHAR2 (255),
    CONSTRAINT PK_PERSONAJES PRIMARY KEY (NOMBRE),
    CONSTRAINT UK_NSS_ACTOR UNIQUE (NSS_ACTOR),
    CONSTRAINT FK_PERSONAJE_ACTOR FOREIGN KEY (NSS_ACTOR) REFERENCES ACTORES (NSS)
    );

    CREATE TABLE TENER_PARENTESCO(
    NOMBRE_PJ VARCHAR2 (60) NOT NULL,
    NOMBRE_PARIENTE VARCHAR2 (60) NOT NULL,
    GRADO_PARENTESCO VARCHAR2 (80),
    CONSTRAINT PK_TENER_PARENTESCO PRIMARY KEY (NOMBRE_PJ,NOMBRE_PARIENTE),
    CONSTRAINT FK_PJ_PERSONAJE FOREIGN KEY (NOMBRE_PJ) REFERENCES PERSONAJES (NOMBRE),
    CONSTRAINT FK_PARIENTE_PERSONAJE FOREIGN KEY (NOMBRE_PARIENTE) REFERENCES PERSONAJES (NOMBRE)
    );

    CREATE TABLE PRINCIPAL(
    NOMBRE VARCHAR2(60),
    FECHA_INI_SERIE DATE,
    CONSTRAINT PK_PRINCIPAL PRIMARY KEY(NOMBRE),
    CONSTRAINT FK_PRINCIPAL_PERSONAJE FOREIGN KEY (NOMBRE) REFERENCES PERSONAJES (NOMBRE)
    );

    CREATE TABLE ZOMBIE(
    NOMBRE VARCHAR2(60) NOT NULL,
    NOMBRE_PJ_KILL VARCHAR2(60),
    DIAS_CONVERTIDO NUMBER,
    DETERIORO VARCHAR2(20),    
    CONSTRAINT PK_ZOMBIE PRIMARY KEY(NOMBRE),
    CONSTRAINT FK_ZOMBIE_PERSONAJE FOREIGN KEY (NOMBRE) REFERENCES PERSONAJES (NOMBRE),
    CONSTRAINT FK_ZOMBIE_PRINCIPAL FOREIGN KEY (NOMBRE_PJ_KILL) REFERENCES PRINCIPAL (NOMBRE)
    );


    CREATE TABLE GRUPO (
    COD_GRUPO NUMBER NOT NULL,
    NOMBRE_GRUPO VARCHAR2(50),
    CONSTRAINT PK_GRUPO PRIMARY KEY(COD_GRUPO));



    CREATE TABLE PERTENECER_GRUPO(
    CODIGO_GRUPO NUMBER NOT NULL,
    PERSONAJE VARCHAR2(60) NOT NULL,
    SER_LIDER VARCHAR2(1) DEFAULT 'N',
    FECHA_ENTRADA DATE,
    CONSTRAINT PK_PERTENECER_GRUPO PRIMARY KEY(CODIGO_GRUPO,PERSONAJE),
    CONSTRAINT FK_PERTENECE_GRUPO FOREIGN KEY (CODIGO_GRUPO) REFERENCES GRUPO (COD_GRUPO),
    CONSTRAINT FK_PERTENECE_PRINCIPAL FOREIGN KEY (PERSONAJE) REFERENCES PRINCIPAL (NOMBRE)        
    );
    
    
    CREATE TABLE TEMPORADAS (
    NUM_TEMPO NUMBER(2) NOT NULL,
    TITULO_TEMPO VARCHAR2(50),
    CONSTRAINT PK_TEMPORADAS PRIMARY KEY(NUM_TEMPO));

    CREATE TABLE CAPITULOS (
    NUM_CAP NUMBER(3) NOT NULL,
    NUM_TEMPO NUMBER(2) NOT NULL,
    FECHA_EMISION DATE,
    DURACION_CAP VARCHAR2(5),
    TITULO_CAP VARCHAR2(50),
    CONSTRAINT PK_CAPITULOS PRIMARY KEY(NUM_CAP,NUM_TEMPO),
    CONSTRAINT FK_CAPITULO_TEMPORADA FOREIGN KEY (NUM_TEMPO) REFERENCES TEMPORADAS (NUM_TEMPO));    
    
    CREATE TABLE LOCALIZACIONES (
    COD_LOC VARCHAR2(10) NOT NULL,
    NOMBRE_LOC VARCHAR2(80),    
    COSTE_LOC NUMBER,
    NUM_ZOMBIES NUMBER,
    NUM_INFRAST NUMBER,
    CONSTRAINT PK_LOCALIZACIONES PRIMARY KEY (COD_LOC));
    
    CREATE TABLE FANS
    (
    USUARIO VARCHAR2(20) NOT NULL,
    NOMBRE VARCHAR2(60),
    PASSWORD_FAN VARCHAR2(20),
    FECHA_INGRESO DATE,
    CONSTRAINT PK_FANS PRIMARY KEY(USUARIO));
    
    
    CREATE TABLE CONVERTIR(
        PRINCIPAL VARCHAR2(60) NOT NULL,
        ZOMBIE VARCHAR2(60) NOT NULL,
        NUM_CAPITULO NUMBER(3) NOT NULL,
        NUM_TEMPORADA NUMBER(2) NOT NULL,
        CONSTRAINT PK_CONVERTIR PRIMARY KEY(PRINCIPAL,ZOMBIE),
        CONSTRAINT UK_CONVERTIR_PJ_TEMP UNIQUE (PRINCIPAL,NUM_CAPITULO,NUM_TEMPORADA),
        CONSTRAINT FK_CONVERTIR_PRINCIPAL FOREIGN KEY (PRINCIPAL) REFERENCES PRINCIPAL (NOMBRE),
        CONSTRAINT FK_CONVERTIR_CAPTIULO FOREIGN KEY (NUM_CAPITULO,NUM_TEMPORADA) REFERENCES CAPITULOS (NUM_CAP,NUM_TEMPO),
        CONSTRAINT FK_CONVERTIR_ZOMBIE FOREIGN KEY (ZOMBIE) REFERENCES ZOMBIE (NOMBRE)  
    );    


    CREATE TABLE ACTUAR (
    CAPITULO NUMBER(3) NOT NULL,
    TEMPORADA NUMBER(2) NOT NULL,
    COD_GRUPO NUMBER NOT NULL,
    COD_LOC VARCHAR2(10) NOT NULL,
    PROBLEMA VARCHAR2(255),
    SOLUCION VARCHAR2(255),
    CONSTRAINT PK_ACTUAR PRIMARY KEY(CAPITULO, TEMPORADA,COD_GRUPO,COD_LOC),
    CONSTRAINT FK_ACTUAR_CAPITULO FOREIGN KEY (CAPITULO, TEMPORADA) REFERENCES CAPITULOS (NUM_CAP, NUM_TEMPO),
    CONSTRAINT FK_ACTUAR_GRUPO FOREIGN KEY (COD_GRUPO) REFERENCES GRUPO (COD_GRUPO),
    CONSTRAINT FK_ACTUAR_LOCALIZACION FOREIGN KEY (COD_LOC) REFERENCES LOCALIZACIONES (COD_LOC));


    CREATE TABLE COMENTAR (
        USUARIO VARCHAR2 (20) NOT NULL,
        NUM_CAP NUMBER(3) NOT NULL,
        NUM_TEMPO NUMBER(2) NOT NULL,
        CODIGO_GRUPO NUMBER NOT NULL,    
        CODIGO_LOC VARCHAR2(10) NOT NULL,
        COMENTARIO VARCHAR2 (4000),
        CONSTRAINT PK_COMENTAR PRIMARY KEY (USUARIO, NUM_CAP, NUM_TEMPO, CODIGO_GRUPO, CODIGO_LOC),
        CONSTRAINT FK_COMENTAR_FANS FOREIGN KEY (USUARIO) REFERENCES FANS(USUARIO),
        CONSTRAINT FK_COMENTAR_LOCALIZACIONES FOREIGN KEY (CODIGO_LOC) REFERENCES LOCALIZACIONES (COD_LOC),
        CONSTRAINT FK_COMENTAR_GRUPO FOREIGN KEY (CODIGO_GRUPO) REFERENCES GRUPO (COD_GRUPO),
        CONSTRAINT FK_COMENTAR_CAPITULO FOREIGN KEY (NUM_CAP, NUM_TEMPO) REFERENCES CAPITULOS (NUM_CAP, NUM_TEMPO)
    );

