
--DROP TABLE ANALISIS;

--DROP TABLE FEDERATIVO;

--DROP TABLE LABORATORIO;

--DROP TABLE ARBITRAR;


--DROP TABLE GOL;

--DROP TABLE JUGAR;

--DROP TABLE ARBITRO;

--DROP TABLE PARTIDO;

--DROP TABLE JUGADOR;

--DROP TABLE EQUIPOS;

    CREATE TABLE EQUIPOS
    (EQUIPO VARCHAR2(50) NOT NULL,
    PAIS VARCHAR2(30),
    SELECCIONADOR VARCHAR2(50),
    CONSTRAINT PK_EQUIPOS PRIMARY KEY(EQUIPO));

    
    CREATE TABLE JUGADOR
    (NOMBRE VARCHAR2(60) NOT NULL,
    DIRECCION VARCHAR2(150),
    PUESTO_HAB VARCHAR2(2),
    FECHA_NAC DATE,   
    EQUIPO_JUGADOR VARCHAR2(50) NOT NULL,
    CONSTRAINT PK_JUGADOR PRIMARY KEY(NOMBRE),
    CONSTRAINT JUGADOR_EQUIPO FOREIGN KEY(EQUIPO_JUGADOR) REFERENCES EQUIPOS (EQUIPO));
  
  
    CREATE TABLE PARTIDO
    (EQUIPO_L VARCHAR2(50) NOT NULL,
    EQUIPO_V VARCHAR2(50) NOT NULL,
    FECHA DATE NOT NULL,
    HORA VARCHAR2(8),
    SEDE VARCHAR2(100),
    RESULTADO_L NUMBER,
    RESULTADO_V NUMBER,
    ASISTENCIA NUMBER,
    CONSTRAINT PK_PARTIDO PRIMARY KEY(EQUIPO_L,EQUIPO_V,FECHA),
    CONSTRAINT PARTIDO_EQUIPO_L FOREIGN KEY(EQUIPO_L) REFERENCES EQUIPOS (EQUIPO),
    CONSTRAINT PARTIDO_EQUIPO_V FOREIGN KEY(EQUIPO_V) REFERENCES EQUIPOS (EQUIPO));
  

    CREATE TABLE ARBITRO
    (NOMBRE VARCHAR2(60) NOT NULL,
    NACIONALIDAD VARCHAR2(15),
    DIRECCION VARCHAR2(150),
    CONSTRAINT PK_ARBITRO PRIMARY KEY(NOMBRE));
 
 
    CREATE TABLE JUGAR
    (NOMBRE_JUG VARCHAR2(60) NOT NULL,
    EQUIPO_L_PART VARCHAR2(50) NOT NULL,
    EQUIPO_V_PART VARCHAR2(50) NOT NULL,
    FECHA_PART DATE NOT NULL,
    MIN_JUGAR NUMBER(3),
    PUESTO_JUGAR VARCHAR2(2),
    DORSAL NUMBER,    
    CONSTRAINT PK_JUGAR PRIMARY KEY (NOMBRE_JUG,EQUIPO_L_PART,EQUIPO_V_PART,FECHA_PART),
    CONSTRAINT JUGAR_JUGADOR FOREIGN KEY(NOMBRE_JUG) REFERENCES JUGADOR (NOMBRE),
    CONSTRAINT JUGAR_EQUIPO FOREIGN KEY(EQUIPO_L_PART,EQUIPO_V_PART,FECHA_PART) REFERENCES PARTIDO (EQUIPO_L,EQUIPO_V,FECHA));


    CREATE TABLE GOL
    (MINUTO NUMBER(3) NOT NULL,
    JUGADOR_GOL VARCHAR2(60) NOT NULL, 
    EQUIPO_L_GOL  VARCHAR2(50) NOT NULL,
    EQUIPO_V_GOL VARCHAR2(50) NOT NULL,
    FECHA_GOL DATE NOT NULL,
    CONSTRAINT PK_GOL PRIMARY KEY (MINUTO, JUGADOR_GOL,EQUIPO_L_GOL,EQUIPO_V_GOL,FECHA_GOL),
    CONSTRAINT GOL_JUGAR FOREIGN KEY(JUGADOR_GOL,EQUIPO_L_GOL,EQUIPO_V_GOL,FECHA_GOL) REFERENCES JUGAR (NOMBRE_JUG,EQUIPO_L_PART,EQUIPO_V_PART,FECHA_PART));


    CREATE TABLE ARBITRAR
    (NOMBRE_ARB VARCHAR2(60) NOT NULL,
    EQUIPO_L_ARB VARCHAR2(50) NOT NULL,
    EQUIPO_V_ARB VARCHAR2(50) NOT NULL,
    FECHA_PAR_ARB DATE NOT NULL,
    FUNCION VARCHAR2(20),
    CONSTRAINT PK_ARBITRAR PRIMARY KEY(NOMBRE_ARB,EQUIPO_L_ARB,EQUIPO_V_ARB,FECHA_PAR_ARB),
    CONSTRAINT ARBITRAR_ARBITRO FOREIGN KEY(NOMBRE_ARB) REFERENCES ARBITRO (NOMBRE),
    CONSTRAINT ARBITRAR_JUGAR FOREIGN KEY(EQUIPO_L_ARB,EQUIPO_V_ARB,FECHA_PAR_ARB) REFERENCES PARTIDO(EQUIPO_L,EQUIPO_V,FECHA));
  

    CREATE TABLE LABORATORIO
    (CIF VARCHAR2(9) NOT NULL,
    NOMBRE VARCHAR2(50),
    DIRECCION VARCHAR2(150),
    TELEFONO NUMBER(9),
    CONSTRAINT PK_LABORATORIO PRIMARY KEY(CIF));
 
   

    CREATE TABLE FEDERATIVO
    (ID_TARJ NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(50),
    TELEFONO NUMBER(9),
    CONSTRAINT PK_FEDERATIVO PRIMARY KEY (ID_TARJ));

  


    CREATE TABLE  ANALISIS
    (JUGADOR VARCHAR2(60) NOT NULL,
    EQUIPO_L VARCHAR2(50) NOT NULL,
    EQUIPO_V VARCHAR2(50) NOT NULL,
    FECHA_PART DATE NOT NULL,
    CIF VARCHAR2(9) NOT NULL,
    ID_TARJETA NUMBER(10) NOT NULL,
    CONSTRAINT PK_ANALISIS PRIMARY KEY (JUGADOR,EQUIPO_L,EQUIPO_V,FECHA_PART,CIF),
    CONSTRAINT UK_ANALISIS UNIQUE(JUGADOR,EQUIPO_L,EQUIPO_V,FECHA_PART,ID_TARJETA),
    CONSTRAINT ANALISIS_JUGAR FOREIGN KEY(JUGADOR,EQUIPO_L,EQUIPO_V,FECHA_PART) REFERENCES JUGAR (NOMBRE_JUG,EQUIPO_L_PART,EQUIPO_V_PART,FECHA_PART),
    CONSTRAINT ANALISIS_LABORATORIO FOREIGN KEY(CIF) REFERENCES LABORATORIO (CIF),
    CONSTRAINT ANALISIS_FEDERATIVO FOREIGN KEY(ID_TARJETA) REFERENCES FEDERATIVO (ID_TARJ)); 
	
-- AÑADIDO AL DISEÑO ORIGINAL    
	ALTER TABLE PARTIDO ADD (
	GRUPO VARCHAR2(2),
	EQUIPO_L_SIGUIENTE VARCHAR2(50),
    EQUIPO_V_SIGUIENTE VARCHAR2(50),
    FECHA_SIGUIENTE DATE,
	CONSTRAINT CHECK_GRUPO CHECK (GRUPO IS NULL OR GRUPO IN ('A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'OC', 'CU', 'SE', 'FI')),
	CONSTRAINT FK_PARTIDO_PARTIDO FOREIGN KEY (EQUIPO_L_SIGUIENTE, EQUIPO_V_SIGUIENTE, FECHA_SIGUIENTE)
	REFERENCES PARTIDO (EQUIPO_L, EQUIPO_V, FECHA));
    
    COMMENT ON COLUMN PARTIDO.GRUPO IS
    'EL CAMPO GRUPO PUEDE SER: A-H (Fase de Grupos) OC (Octavos) CU (Cuartos) SE (Semifinal) FI (Final)';
