-- Adrián Navarro Gabino

-- EJERCICIO 7

-- CREA UN JUGADOR CON TU NOMBRE Y PONLO EN LA SELECCIÓN ESPAÑOLA

INSERT INTO JUGADOR
(NOMBRE, EQUIPO_JUGADOR, TELEFONO, TIPO_JUGADOR)
VALUES
('ADRIÁN NAVARRO', 'ESPAÑA', 120, 'ESPAÑOL');