-- Adrián Navarro Gabino

-- EJERCICIO 3

-- OBTÉN TODOS LOS JUGADORES QUE HAYAN JUGADO MÁS
-- DE 45 MINUTOS, QUE NO SALGAN REPETIDOS. 

SELECT DISTINCT NOMBRE_JUG
FROM JUGAR
WHERE MIN_JUGAR > 45
ORDER BY NOMBRE_JUG;