-- Adrián Navarro Gabino

-- EJERCICIO 8

-- INSERTA UN PARTIDO ESPAÑA FRANCIA CON RESULTADO
-- QUE QUIERAS QUE SE HAYA  JUGADO 05/01/2018, PUEDES
-- DEJAR CAMPOS EN BLANCO

INSERT INTO PARTIDO
(EQUIPO_L, EQUIPO_V, FECHA, RESULTADO_L, RESULTADO_V)
VALUES
('ESPAÑA', 'FRANCIA', TO_DATE('05/01/2018','DD/MM/YYYY') , 2, 2);