--  DROP TABLE TENER_ESCALA;
--  
--  DROP TABLE VOLAR;
--  
--  DROP TABLE AVIONES;
--  
--  DROP TABLE PROGRAMA_VUELO;
--  
--  DROP TABLE DIRECTOR;

--  DROP TABLE AEROPUERTOS;

--  DROP TABLE TMP_AEROPUERTOS;

--  DROP TABLE TMP_AEROLINEAS;

  --DROP TABLE TMP_AEROPUERTOS2;


    CREATE TABLE DIRECTOR (
      DNI VARCHAR2(9) NOT NULL,
      COD_AEROPUERTO VARCHAR2(3) NOT NULL,
      NOMBRE VARCHAR2(60),
      DIRECCION VARCHAR2(100),
      TELEFONO NUMBER(9),
      PAIS VARCHAR2(60),
      DNI_CONTR VARCHAR2(9),
        CONSTRAINT PK_DIRECTOR PRIMARY KEY (DNI),
        CONSTRAINT UK_AEROPUERTO UNIQUE (COD_AEROPUERTO)
    );

    CREATE TABLE AEROPUERTOS (
      CODIGO VARCHAR2(3) NOT NULL,
      NOMBRE VARCHAR2(60),
      CIUDAD VARCHAR2(60),
      PAIS VARCHAR2(60),
      PROVINCIA VARCHAR2(60),
      NOMBRE_ALTERNATIVO VARCHAR2(100), 
      PAIS_ALTERNATIVO VARCHAR2(60),
        CONSTRAINT PK_AEROPUERTOS PRIMARY KEY (CODIGO)
    );


    CREATE TABLE TMP_AEROPUERTOS2
    (
      COD_IATA  VARCHAR2(4),
      COD_ICAO  VARCHAR2(5),
      NOMBRE    VARCHAR2(45)
    );

    CREATE TABLE PROGRAMA_VUELO (
      NUM_VUELO VARCHAR2(7) NOT NULL,
      COD_AERO_DESPEGAR VARCHAR2(3) NOT NULL,
      COD_AERO_ATERRIZAR VARCHAR2(3) NOT NULL,
      LINEA_AEREA VARCHAR2(60),
      DIAS_SEMANA VARCHAR2(100), 
        CONSTRAINT PK_PROGRAMA_VUELO PRIMARY KEY (NUM_VUELO)
    );

    CREATE TABLE AVIONES (
      CODIGO VARCHAR2(5) NOT NULL,
      LINEA_AEREA VARCHAR2(60),
      MODELO VARCHAR2(30),
      CAPACIDAD NUMBER(3),
        CONSTRAINT PK_AVIONES PRIMARY KEY (CODIGO)
    );


    CREATE TABLE VOLAR (
      NUM_VUELO VARCHAR2(7) NOT NULL,
      COD_AVION VARCHAR2(5) NOT NULL,
      FECHA_VUELO DATE NOT NULL,
      PLAZAS_OCUPADAS NUMBER,
        CONSTRAINT PK_VOLAR PRIMARY KEY (NUM_VUELO, COD_AVION, FECHA_VUELO)
    );

    CREATE TABLE TENER_ESCALA (
      NUM_VUELO VARCHAR2(7) NOT NULL,
      COD_AVION VARCHAR2(5) NOT NULL,
      FECHA_VUELO DATE NOT NULL,
      COD_AEROPUERTO VARCHAR2(3) NOT NULL,
      NUMERO_ESCALA NUMBER(1),
      PASAJEROS_BAJAN NUMBER(3),
      PASAJEROS_SUBEN NUMBER(3),
        CONSTRAINT PK_TENER_ESCALA PRIMARY KEY (NUM_VUELO, COD_AVION, FECHA_VUELO, COD_AEROPUERTO)
    );

    ALTER TABLE DIRECTOR ADD (CONSTRAINT FK_DIRECTOR_DIRECTOR FOREIGN KEY (DNI_CONTR) REFERENCES DIRECTOR (DNI),
                              CONSTRAINT FK_DIRECTOR_AEROPUERTOS FOREIGN KEY (COD_AEROPUERTO) REFERENCES AEROPUERTOS (CODIGO));

    ALTER TABLE PROGRAMA_VUELO ADD (CONSTRAINT FK_VOLAR_AERO_DESPEGAR FOREIGN KEY (COD_AERO_DESPEGAR) REFERENCES AEROPUERTOS (CODIGO),
                              CONSTRAINT FK_VOLAR_AERO_ATERRIZAR FOREIGN KEY (COD_AERO_ATERRIZAR) REFERENCES AEROPUERTOS (CODIGO));

    ALTER TABLE VOLAR ADD (CONSTRAINT FK_VOLAR_PROGRAMA FOREIGN KEY (NUM_VUELO) REFERENCES PROGRAMA_VUELO (NUM_VUELO),
                           CONSTRAINT FK_VOLAR_AVIONES FOREIGN KEY (COD_AVION) REFERENCES AVIONES (CODIGO));

    ALTER TABLE TENER_ESCALA ADD (CONSTRAINT FK_TENER_ESCALA_VOLAR FOREIGN KEY (NUM_VUELO, COD_AVION, FECHA_VUELO) REFERENCES VOLAR (NUM_VUELO, COD_AVION, FECHA_VUELO),
                                  CONSTRAINT FK_TENER_ESCALA_AEROP FOREIGN KEY (COD_AEROPUERTO) REFERENCES AEROPUERTOS (CODIGO));




  
