-- Adrián Navarro Gabino

-- EJERCICIO 1

--  Inserta un árbitro que se llame James Bond. Y un partido con nombre
-- INGLATERRA – ESPAÑA con la fecha que quieras. Haz que el árbitro sea
-- el colegiado principal ('PRINCIPAL'). Y ahora obtén en una SELECT el
-- resultado, el aforo y la nacionalidad del árbitro, de los datos que
-- acabas de insertar.

INSERT INTO ARBITRO
(NOMBRE, NACIONALIDAD)
VALUES
('JAMES BOND', '(ENG)');

INSERT INTO PARTIDO
(EQUIPO_L, EQUIPO_V, FECHA, RESULTADO_L, RESULTADO_V, ASISTENCIA)
VALUES
('INGLATERRA', 'ESPAÑA', TO_DATE('06/02/2018','DD/MM/YYYY'), 2, 1, 30000);

INSERT INTO ARBITRAR
(NOMBRE_ARB, EQUIPO_L_ARB, EQUIPO_V_ARB, FECHA_PAR_ARB, FUNCION)
(SELECT ARB.NOMBRE, PART.EQUIPO_L, PART.EQUIPO_V, PART.FECHA, 'ARBITRO PRICIPAL'
FROM ARBITRO ARB, PARTIDO PART
WHERE ARB.NOMBRE='JAMES BOND' AND FECHA=TO_DATE('06/02/2018','DD/MM/YYYY'));

SELECT PART.RESULTADO_L, PART.RESULTADO_V, PART.ASISTENCIA, ARB.NACIONALIDAD
FROM ARBITRO ARB, PARTIDO PART
WHERE ARB.NOMBRE = 'JAMES BOND' AND
PART.EQUIPO_L='INGLATERRA' AND PART.EQUIPO_V='ESPAÑA' AND
PART.FECHA=TO_DATE('06/02/2018','DD/MM/YYYY');