-- Adrián Navarro Gabino

-- EJERCICIO 2

-- ACTUALIZAR EL CAMPO TELEFONO: 

-- 120 A LOS JUGADORES DE ‘ESPAÑA’   
-- 90 A LOS JUGADORES DE 'ARGENTINA' 
-- 100 A LOS JUGADORES  DE 'BRASIL' 
-- 110 A LOS JUGADORES QUE NO SEAN ALEMANIA, FRANCIA NI ITALIA.

-- FINALMENTE CREAR UN CAMPO QUE DIGA TIPO_JUGADOR Y PARA
-- ACTUALIZARLO A 'ESPAÑOL' SI LOS TELEFONOS SON MAYORES QUE 111 Y A
-- ‘EXTRANJERO’ SI NO ES ASÍ 

UPDATE JUGADOR
    SET TELEFONO = 120
WHERE EQUIPO_JUGADOR = 'ESPAÑA';

UPDATE JUGADOR
    SET TELEFONO = 90
WHERE EQUIPO_JUGADOR = 'ARGENTINA';

UPDATE JUGADOR
    SET TELEFONO = 100
WHERE EQUIPO_JUGADOR = 'BRASIL';

UPDATE JUGADOR
    SET TELEFONO = 110
WHERE EQUIPO_JUGADOR NOT IN
('ESPAÑA','ARGENTINA','BRASIL','ALEMANIA','FRANCIA','ITALIA');

ALTER TABLE JUGADOR ADD
(
    TIPO_JUGADOR VARCHAR2(10)
);

UPDATE JUGADOR
    SET TIPO_JUGADOR = 'ESPAÑOL'
WHERE TELEFONO > 111;

UPDATE JUGADOR
    SET TIPO_JUGADOR = 'EXTRANJERO'
WHERE TELEFONO <= 111;