-- Adrián Navarro Gabino

-- EJERCICIO 9

-- INSERTA EL JUGADOR CREADO EN EL EJERCICIO 7,
-- Y HAZ QUE HAYA JUGADO EN TODOS LOS  PARTIDOS QUE
-- HAYA JUGADO ESPAÑA TANTO LOCAL COMO VISITANTE, A
-- EXCEPCIÓN DEL  PARTIDO DEL EJERCICIO 8

INSERT INTO JUGAR
(NOMBRE_JUG, EQUIPO_L_PART, EQUIPO_V_PART, FECHA_PART)
(SELECT JUGADOR.NOMBRE, PARTIDO.EQUIPO_L, PARTIDO.EQUIPO_V, PARTIDO.FECHA
FROM JUGADOR, PARTIDO
WHERE JUGADOR.NOMBRE='ADRIÁN NAVARRO' AND
(PARTIDO.EQUIPO_L='ESPAÑA' OR PARTIDO.EQUIPO_V='ESPAÑA') AND
PARTIDO.FECHA!=TO_DATE('05/01/2018','DD/MM/YYYY'));