-- Adrián Navarro Gabino

-- EJERCICIO 6

--  BORRA LOS JUGADORES CON TELEFONO A NULL.
-- ¿TE FALLA?. EXPLICA POR QUÉ SI O POR  QUÉ NO.

DELETE JUGADOR
WHERE TELEFONO IS NULL;

-- FALLA PORQUE LA TABLA JUGADOR ES PADRE DE LA TABLA JUGAR
-- PARA PODER BORRAR A ESTOS JUGADORES, HABRÍA QUE HABER
-- DEFINIDO LAS FK DE JUGAR CON ON DELETE CASCADE.
