-- Adrián Navarro Gabino

-- EJERCICIO 5

-- JUGADORES CON NOMBRE QUE TERMINEN EN VOCAL

SELECT NOMBRE
FROM JUGADOR
WHERE NOMBRE LIKE '%A' OR NOMBRE LIKE '%E' OR
NOMBRE LIKE '%I' OR NOMBRE LIKE '%O' OR NOMBRE = '%U'
ORDER BY NOMBRE;