-- Adrián Navarro Gabino

-- EJERCICIO 10

-- REDUCE EL CAMPO HORA DE PARTIDO A VARCHAR2(2). ¿TE FALLA?,
-- CREA UN CAMPO  CLON QUE SE LLAME HORA2, Y LUEGO VACÍA EL
-- CAMPO HORA. ¿PUEDES AHORA REDUCIRLO A  VARCHAR(2)?

ALTER TABLE PARTIDO ADD
(
    HORA2 VARCHAR2(8)
);

UPDATE PARTIDO
    SET HORA2 = HORA;

UPDATE PARTIDO
    SET HORA = NULL;
    
ALTER TABLE PARTIDO MODIFY
(
    HORA VARCHAR2(2)
);